sudo: false
language : python
python:
  - 3.4
  - 3.5
  - 3.6

before_install:
  - cd code

install:
  - pip install pbars
  - pip instsll termisize
  - python setup.py install

before_script:
  - cd ../tests

script:
  - python build_1.py
  - python build_2.py
  - python build_3.py
  - python build_4.py
