sudo: true
language : python
python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install pynimations
  - pip install pbars
  - pip install Striker

before_script:
  - cd tests

script:
  - striker
  - sudo striker
 # - python build_1.py
  #- python build_2.py
  #- python build_3.py
